s = set()
n = input("Enter a nuber-1: ")
s.add(int(n))
n = input("Enter a nuber-2: ")
s.add(int(n))
n = input("Enter a nuber-3: ")
s.add(int(n))
n = input("Enter a nuber-4: ")
s.add(int(n))
n = input("Enter a nuber-5: ")
s.add(int(n))
n = input("Enter a nuber-6: ")
s.add(int(n))
n = input("Enter a nuber-7: ")
s.add(int(n))
n = input("Enter a nuber-8: ")
s.add(int(n))
print(s)